-- Aug 28, 2014 11:58:45 AM VET
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
CREATE TABLE HR_JournalLine (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , EndTime DATE DEFAULT NULL , HR_Concept_ID NUMBER(10) NOT NULL, HR_Journal_ID NUMBER(10) NOT NULL, HR_JournalLine_ID NUMBER(10) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, StartTime DATE DEFAULT NULL , Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT HR_JournalLine_Key PRIMARY KEY (HR_JournalLine_ID))
;

