-- Aug 27, 2014 11:58:57 AM VET
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
CREATE TABLE HR_IncidenceGroup (AD_Client_ID NUMBER(10) NOT NULL, AD_Color_ID NUMBER(10) DEFAULT NULL , AD_Org_ID NUMBER(10) NOT NULL, Blue NUMBER(10) DEFAULT NULL , Blue_1 NUMBER(10) DEFAULT NULL , ColorType CHAR(1) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , Green NUMBER(10) DEFAULT NULL , Green_1 NUMBER(10) DEFAULT NULL , HR_IncidenceGroup_ID NUMBER(10) DEFAULT NULL , ImageAlpha NUMBER DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LineDistance NUMBER(10) DEFAULT NULL , LineWidth NUMBER(10) DEFAULT NULL , Name NVARCHAR2(60) DEFAULT NULL , Red NUMBER(10) DEFAULT NULL , Red_1 NUMBER(10) DEFAULT NULL , RepeatDistance NUMBER(10) DEFAULT NULL , StartPoint NVARCHAR2(22) DEFAULT NULL , Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, Value NVARCHAR2(60) DEFAULT NULL )
;

