-- Oct 13, 2014 3:53:37 PM VET
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
UPDATE AD_Column SET IsKey='N',Updated=TO_DATE('2014-10-13 15:53:37','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Column_ID=1000156
;

-- Oct 13, 2014 3:53:39 PM VET
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
CREATE TABLE HR_Journal (AD_Client_ID NUMBER(10) NOT NULL, AD_Color_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Blue NUMBER(10) NOT NULL, Blue_1 NUMBER(10) DEFAULT NULL , ColorType CHAR(1) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , EndTime DATE NOT NULL, Green NUMBER(10) NOT NULL, Green_1 NUMBER(10) NOT NULL, HR_Journal_ID NUMBER(10) DEFAULT NULL , ImageAlpha NUMBER DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, LineDistance NUMBER(10) DEFAULT NULL , LineWidth NUMBER(10) DEFAULT NULL , Name NVARCHAR2(60) NOT NULL, Red NUMBER(10) DEFAULT NULL , Red_1 NUMBER(10) DEFAULT NULL , RepeatDistance NUMBER(10) DEFAULT NULL , StartPoint NVARCHAR2(22) DEFAULT NULL , StartTime DATE NOT NULL, TimeSlotEnd DATE NOT NULL, TimeSlotStart DATE NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, Value NVARCHAR2(60) NOT NULL, CONSTRAINT HR_Journal_Key PRIMARY KEY (HR_Journal_ID))
;

