-- Oct 14, 2014 11:07:17 AM VET
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
CREATE TABLE HR_IGConcept (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, HR_Concept_ID NUMBER(10) NOT NULL, HR_IncidenceGroup_ID NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT HR_IGConcept_Key PRIMARY KEY (HR_Concept_ID, HR_IncidenceGroup_ID))
;

